### ISSUE TITLE
POST /products 상품 등록 오류 해결

### ISSUE THREAD

**Issue by deepredk** [FC-WhyWrongThoguhtRight/MWT-Market#61]

**Comment by whdgns5059** [comment]
아마 원빈님과 동훤님이 관련 로직 수정하시면서 같이 서버 정상작동이 되는것같습니다.
로컬 및 서버 테스트 정상작동 확인 하였습니다.
해당 이슈는 close 하도록 하겠습니다.

서버 Postman 테스트
![image](https://github.com/FC-WhyWrongThoguhtRight/MWT-Market/assets/40512982/fd44e6b4-b547-4b2e-8af4-cee392d38fe8)
서버 DB 에 상품 정보 및 이미지 적재 확인
![image](https://github.com/FC-WhyWrongThoguhtRight/MWT-Market/assets/40512982/0e56e518-c275-4ce5-9f56-8966e25ea427)
